apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: html-app-ingress
spec:
  rules:
  - host: html-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: html-app-service
            port:
              number: 80